title: Beepony
email: beeponky@gmail.com
description: Connecting the Dots.
url: "https://beepony.github.io"
baseurl: ""
lang: zh-CN
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 这些文件只用于维护，不会被发布到网站。
exclude:
  - README.md
  - POST_TEMPLATE.md
  - Gemfile
  - Gemfile.lock
